### ISSUE TITLE
Downloads from Github

### ISSUE THREAD

**Issue by pecigonzalo** [linux-china/dx#1]
Hi! Thanks for this port, I was looking for something exactly like this. Im having some issues running it.

The error I get is:
```
❯ dx demo.ts
Download https://raw.githubusercontent.com/tmp/tmp.o5gMIsUmRZ/demo.ts
error: Uncaught (in promise) TypeError: Import 'https://raw.githubusercontent.com/tmp/tmp.o5gMIsUmRZ/demo.ts' failed: 400 Bad Request
    at async https://raw.githubusercontent.com/linux-china/dx/master/cli.ts:14:5
```

`/tmp/tmp.o5gMIsUmRZ/demo.ts` is the path in my system to the `demo.ts` file, so it seems like its not loading from local and instead trying to resolve it remotely.

What I did:
- Install deno with Nix
- Install dx with `deno install -A --unstable -n dx https://denopkg.com/linux-china/dx/cli.ts`
- Create a tmp directory to test
- Create a file called `demo.ts` with the demo content
- Try to run it

Thanks!

**Comment by linux-china** [comment]
Yes. it's a bug from local system, and I added "file://" prefix to load scripts from local. 

please try again. 

```
deno install -A --unstable -n dx -f -r https://denopkg.com/linux-china/dx/cli.ts
``` 

Sorry for delay answer.

**Comment by pecigonzalo** [comment]
No worries! Ill give it a try, much appreciated.

**Comment by pecigonzalo** [comment]
Awesome! It works now!
